name: Mission

on:
  schedule:
    - cron: '23 11 * * *'
  workflow_dispatch: 
    inputs:
      run_backup:
        description: 'run backup.py?'
        required: false
        default: false    
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v5
      with:
        fetch-depth: 0

    - name: set env
      uses: actions/setup-python@v6
      with:
        python-version: '3.12'

    - name: req
      run: |
        pip install akshare pandas pyarrow pytz baostock numpy

    - name: run main
      # 定时触发，或者手动触发且未勾选 backup 时，运行 data.py
      if: ${{ github.event_name == 'schedule' || github.event.inputs.run_backup == 'false' }}
      run: python data.py   
    
    - name: run backup
      # 只有手动触发且明确勾选 backup 时，才运行 backup.py
      if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.run_backup == 'true' }}
      run: python backup.py

    - name: push data
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Auto update stock data: $(date +'%Y-%m-%d')" || exit 0
        git pull origin main --rebase -X theirs  
        git push origin main
